"""
Animator Node — handles execution tracing and Manim script generation.
Part of the Animator Lambda module.
"""
import os, json, subprocess
from .tools.tracer import trace_to_file

ANIM_DIR = "video_temp/animations"

def _generate_manim_script(problem_title: str, pattern: str, trace_path: str, output_path: str):
    """Generates a Python script that uses Manim to visualize the execution trace."""
    
    # Load trace data
    trace_data = []
    if os.path.exists(trace_path):
        with open(trace_path, "r") as f:
            trace_data = json.load(f)
            
    header = f'"""\nManim Animation for {problem_title}\nGenerated by LeetOne Animator\n"""\nfrom manim import *\nimport json\n\n'
    
    # Basic Code-Centric Template
    script_body = f"""
class AlgorithmScene(Scene):
    def construct(self):
        title = Text("{problem_title}").to_edge(UP)
        self.play(Write(title))
        
        # Load Trace (Embedded directly into script for portability)
        trace = {json.dumps(trace_data[:30])} # Limit for MVP stability
        
        code_box = Rectangle(width=10, height=5, color=BLUE).shift(DOWN*0.5)
        self.play(Create(code_box))
        
        # Logic for iterating through trace would go here
        # For now, we show a professional summary of the algorithm's state
        status = Text(f"Pattern detected: {pattern}", font_size=32).next_to(code_box, DOWN)
        self.play(FadeIn(status))
        self.wait(2)
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header + script_body)
    print(f"  [animator_node] Generated Manim script: {output_path}")

def animator_node(state: dict) -> dict:
    """
    Animator Node (Agent #2) - Generates Manim scripts and tracers.
    """
    chapters = state.get("chapters", [])
    problem_title = state.get("problem_title", "Unknown")
    solutions_data = state.get("solutions_data", [])
    cache_dir = state.get("cache_dir", "video_temp")
    pattern = state.get("pattern", "generic")
    
    print(f"[animator_node] Processing {len(chapters)} animation segments...")
    
    # 1. Identify optimal code for tracing...
    # (Existing optimal_code/method_name logic remains the same)
    optimal_code = ""
    for sol in solutions_data:
        if sol.get("approach") == "optimal" or "optimal" in sol.get("href", "").lower():
            optimal_code = sol.get("code", "")
            break
    if not optimal_code and solutions_data:
        optimal_code = solutions_data[0].get("code", "")

    method_name = "solve"
    if "def " in optimal_code:
        import re
        match = re.search(r"def (\w+)\(self", optimal_code)
        if match:
            method_name = match.group(1)

    # 2. Perform Execution Trace (Ground Truth)
    trace_path = os.path.join(cache_dir, "trace.json")
    if optimal_code:
        try:
            prob_data = state.get("problem_data", {})
            raw_tc = prob_data.get("example_testcases", "[]")
            import ast
            tc_input = ast.literal_eval(raw_tc.split("\n")[0])
            if not isinstance(tc_input, list): tc_input = [tc_input]

            print(f"  [animator_node] Tracing ground truth for input: {tc_input}")
            trace_to_file(optimal_code, method_name, tc_input, trace_path)
        except Exception as e:
            print(f"  [animator_node] Trace failed: {e}")

    # 3. Generate Manim Scripts for Dry Run Chapters
    updated_chapters = []
    for ch in chapters:
        new_ch = ch.copy()
        if ch.get("is_dry_run"):
            anim_path = f"{cache_dir}/anim_{ch['segment_id']}.py"
            _generate_manim_script(problem_title, pattern, trace_path, anim_path)
            new_ch["anim_script"] = anim_path
        updated_chapters.append(new_ch)
    
    return {"chapters": updated_chapters}
